# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: |
  Thank you ğŸ’– and congrats ğŸ‰ for reporting your first issue in this repository.

  A maintainer will review this issue and apply the corresponding labels shortly.

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: |
  Welcome to Devopness open source projects! ğŸ‘‹

  Thank you ğŸ’– and congrats ğŸ‰ for opening your first pull request in this repository!
  
  Someone from the Devopness team will review this PR once all its automated checks are passing. âœ… 
  
  Please be patient! ğŸ™ 
  * We might take a few days, but we always review all PRs as soon as we can. :-)
  
  In the meantime, if you haven't already: 
  - Sign up for a free Devopness account at https://www.devopness.com/
  - Read our [Code of Conduct](https://github.com/devopness/devopness/blob/main/CODE_OF_CONDUCT.md)
  - Read our [Contributing guidelines](https://github.com/devopness/devopness/blob/main/CONTRIBUTING.md)

  Also, **please consider**:
  - â­ Star this repository
  - ğŸ“£ Post about Devopness on social networks, Discord, LinkedIn, Slack, Twitter, ...

  Hope you have a great time contributing and learning around here! ğŸ˜„
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request! ğŸ‰ğŸ‰ğŸ‰
