version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    storybook:
      patterns:
        - "storybook"
        - "@storybook/*"
        - "eslint-plugin-storybook"
  ignore:
  - dependency-name: eslint
    versions:
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@openapitools/openapi-generator-cli"
    versions:
    - 2.1.23
    - 2.1.25
    - 2.2.1
    - 2.2.3
    - 2.2.4
    - 2.2.5
  - dependency-name: "@types/jest"
    versions:
    - 26.0.22
  - dependency-name: husky
    versions:
    - 5.2.0
  - dependency-name: typescript
    versions:
    - 4.1.4

- package-ecosystem: pip
  directories:
    - "/packages/sdks/python"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  
- package-ecosystem: npm
  directory: "/docs"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  groups:
    fumadocs:
      patterns:
        - "fumadocs-*"
