blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Ideas & Feature Requests
    url: https://github.com/devopness/devopness/discussions/categories/ideas-feature-requests
    about: Share your ideas and request features you want to see added to Devopness
