blank_issues_enabled: false
contact_links:
  - name: ğŸ’¡ Ideas & Feature Requests
    url: https://github.com/devopness/devopness/discussions/categories/ideas-feature-requests
    about: Discuss ideas or request features you want to see added to Devopness
  - name: ğŸ’¬ General Discussions
    url: https://github.com/devopness/devopness/discussions/categories/general
    about: Chat about anything related to Devopness
  - name: â“ Ask for help
    url: https://github.com/devopness/devopness/discussions/categories/help
    about: Ask the community for help or ask questions about the product
