name: PR - Labeler

on:
  pull_request_target:
    # triggers on `pull_request_target` as this is a fork-based repository
    # for security reasons, `npm` or other code execution jobs must not
    # be executed on this workflow
    types:
      - opened
      - reopened
      - synchronize

jobs:
  triage:
    runs-on: ubuntu-latest
    name: Label PR - Triage
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout PR Code
        uses: actions/checkout@v6
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          persist-credentials: true
          fetch-depth: 0

      - name: Label PR - Step
        uses: actions/labeler@v6
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/labeler-pr.yml
          sync-labels: true
